name: PMD Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pmd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'pmd-ruleset.xml'
          sourcePath: 'gachapy'

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: pmd-report.sarif
